[package]
name = "InvoiceOS"
version = "1.0.0"

[addresses]
# Your existing address
invoice_rwa = "_"

# ADD THIS LINE:
message_board_addr = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", rev = "mainnet", subdir = "aptos-framework" }
